name: Validate Generated Files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          sudo snap install hugo
          pip install html5validator

      - name: Build Example Site
        run: |
          cd exampleSite/
          hugo --minify

      - name: Validate Generated Files
        run: html5validator --root exampleSite/public/ --also-check-css --ignore katex ontouch
